config/routes.rb
Menuproject::Application.routes.draw do
  devise_for :users

  resources :menuitems
  root :to => "menuitems#index"


end

app/models/menu.rb
class Menu < ActiveRecord::Base
  attr_accessible :meal_type, :publish_date
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  attr_accessible :description, :image, :ingredients, :item_type, :name, :nutrition
end

app/models/menuitem.rb
class Menuitem < ActiveRecord::Base
  attr_accessible :description, :ingredients, :name, :nutrition
end

app/models/preperation.rb
class Preperation < ActiveRecord::Base
  attr_accessible :menu_id, :menu_item_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/menuitems_controller.rb
class MenuitemsController < ApplicationController
  # GET /menuitems
  # GET /menuitems.json
  def index
    @menuitems = Menuitem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @menuitems }
    end
  end

  # GET /menuitems/1
  # GET /menuitems/1.json
  def show
    @menuitem = Menuitem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @menuitem }
    end
  end

  # GET /menuitems/new
  # GET /menuitems/new.json
  def new
    @menuitem = Menuitem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @menuitem }
    end
  end

  # GET /menuitems/1/edit
  def edit
    @menuitem = Menuitem.find(params[:id])
  end

  # POST /menuitems
  # POST /menuitems.json
  def create
    @menuitem = Menuitem.new(params[:menuitem])

    respond_to do |format|
      if @menuitem.save
        format.html { redirect_to @menuitem, notice: 'Menuitem was successfully created.' }
        format.json { render json: @menuitem, status: :created, location: @menuitem }
      else
        format.html { render action: "new" }
        format.json { render json: @menuitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /menuitems/1
  # PUT /menuitems/1.json
  def update
    @menuitem = Menuitem.find(params[:id])

    respond_to do |format|
      if @menuitem.update_attributes(params[:menuitem])
        format.html { redirect_to @menuitem, notice: 'Menuitem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @menuitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menuitems/1
  # DELETE /menuitems/1.json
  def destroy
    @menuitem = Menuitem.find(params[:id])
    @menuitem.destroy

    respond_to do |format|
      format.html { redirect_to menuitems_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menuitems_helper.rb
module MenuitemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Menuproject</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/menuitems/_form.html.erb
<%= form_for(@menuitem) do |f| %>
  <% if @menuitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menuitem.errors.count, "error") %> prohibited this menuitem from being saved:</h2>

      <ul>
      <% @menuitem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :nutrition %><br />
    <%= f.text_area :nutrition %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br />
    <%= f.text_area :ingredients %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menuitems/edit.html.erb
<h1>Editing menuitem</h1>

<%= render 'form' %>

<%= link_to 'Show', @menuitem %> |
<%= link_to 'Back', menuitems_path %>

app/views/menuitems/index.html.erb
<h1>Listing menuitems</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Nutrition</th>
    <th>Ingredients</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @menuitems.each do |menuitem| %>
  <tr>
    <td><%= menuitem.name %></td>
    <td><%= menuitem.description %></td>
    <td><%= menuitem.nutrition %></td>
    <td><%= menuitem.ingredients %></td>
    <td><%= link_to 'Show', menuitem %></td>
    <td><%= link_to 'Edit', edit_menuitem_path(menuitem) %></td>
    <td><%= link_to 'Destroy', menuitem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Menuitem', new_menuitem_path %>

app/views/menuitems/new.html.erb
<h1>New menuitem</h1>

<%= render 'form' %>

<%= link_to 'Back', menuitems_path %>

app/views/menuitems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @menuitem.name %>
</p>

<p>
  <b>Description:</b>
  <%= @menuitem.description %>
</p>

<p>
  <b>Nutrition:</b>
  <%= @menuitem.nutrition %>
</p>

<p>
  <b>Ingredients:</b>
  <%= @menuitem.ingredients %>
</p>


<%= link_to 'Edit', edit_menuitem_path(@menuitem) %> |
<%= link_to 'Back', menuitems_path %>